spring:
  application:
    name: auction-consumer
  data:
    mongodb:
      uri: mongodb://localhost:27017/bts-auction-db
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
server:
  port: 9091
